
automatic_scaling: 
  max_instances: 100
  max_pending_latency: automatic
  min_instances: 2
  min_pending_latency: 30ms
  target_cpu_utilization: 0.65
entrypoint: "gunicorn -b :8080 -w 3 main:app"
handlers: 
  - 
    http_headers: 
      Access-Control-Allow-Origin: "*"
    static_dir: static/images
    url: /images
instance_class: F4
runtime: python39
